export const FADE = "FADE";
export const ZOOM = "ZOOM";
export const SLIDE = "SLIDE";
export const NO_ANIMATION = "NO_ANIMATION";

export const NO_ANIMATION_BLOCK = "NO_ANIMATION_BLOCK";
export const ZOOM_ANIMATION_BLOCK = "ZOOM_ANIMATION_BLOCK";
export const FADE_ANIMATION_BLOCK = "FADE_ANIMATION_BLOCK";
export const SLIDE_ANIMATION_BLOCK = "SLIDE_ANIMATION_BLOCK";
export const RANDOM_ANIMATION_BLOCK = "RANDOM_ANIMATION_BLOCK";
export const PAUSE_ANIMATION_BLOCK = "PAUSE_ANIMATION_BLOCK";
